new Ensemble and changes
harelm4/Embible-Backend pull request #33
Opened 2023-05-20 12:17 UTC by nivfono

2023-05-20 20:02 UTC, Eldar-Ka requested changes

2023-05-20 20:02 UTC, Eldar-Ka commented on src/model/ensemble_v2.py
> +    def calculate_new_scores(self, list1, list2, weight1, weight2):
please add docomentation

2023-05-20 20:02 UTC, Eldar-Ka commented on src/model/single_char_model.py
> +class single_char_model(StandardModel):
why do we need this model?

2023-05-20 20:02 UTC, Eldar-Ka commented on src/space_predictor/Iterative_space_predictor.py
> +    def replace_with_spaces(self, text, indices):
add docomentation please

2023-05-21 16:19 UTC, harelm4 commented on src/model/Char_model.py
> +        comb_chars=self.limit_product(char_lists,1000)#list(itertools.product(*char_lists))[:1000]
revert to old working version

2023-05-21 18:31 UTC, Eldar-Ka approved these changes

2023-05-21 18:31 UTC, Eldar-Ka commented on src/model/ensemble_union.py
> +
add docomentation please

2023-05-21 18:31 UTC, Eldar-Ka approved these changes

2023-05-22 09:54 UTC, merged